import ssl
ssl._create_default_https_context = ssl._create_unverified_context

import streamlit as st
import tempfile
import os
from transcriber import process_input
from agents import analyse_meeting

# ─── PAGE CONFIG ───
st.set_page_config(
    page_title="AI Meeting Summariser",
    page_icon="🎙️",
    layout="wide"
)

# ─── HEADER ───
st.title("🎙️ AI Meeting Summariser")
st.markdown("Upload a meeting transcript or audio file and get instant AI-powered analysis.")
st.divider()

# ─── FILE UPLOAD ───
st.subheader("📁 Upload Your Meeting")

uploaded_file = st.file_uploader(
    "Choose a file",
    type=["txt", "mp3", "mp4", "wav", "m4a", "ogg"],
    help="Supported formats: TXT, MP3, MP4, WAV, M4A, OGG"
)

if uploaded_file is not None:
    st.success(f"✅ File uploaded: {uploaded_file.name}")

    # Show file details
    col1, col2 = st.columns(2)
    with col1:
        st.metric("File Name", uploaded_file.name)
    with col2:
        st.metric("File Size", f"{uploaded_file.size / 1024:.1f} KB")

    st.divider()

    # ─── PROCESS BUTTON ───
    if st.button("🚀 Analyse Meeting", use_container_width=True):

        # Save uploaded file to temp location
        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=os.path.splitext(uploaded_file.name)[1]
        ) as tmp_file:
            tmp_file.write(uploaded_file.read())
            tmp_path = tmp_file.name

        try:
            # ─── TRANSCRIPTION ───
            with st.spinner("📝 Processing file..."):
                transcript = process_input(tmp_path)

            # Show transcript
            with st.expander("📄 View Transcript", expanded=False):
                st.text_area("Transcript", transcript, height=200)

            st.divider()

            # ─── AGENT ANALYSIS ───
            st.subheader("🤖 AI Analysis")

            with st.spinner("🧠 Running AI agents — this may take 1-2 minutes..."):
                results = analyse_meeting(transcript)

            # ─── DISPLAY RESULTS ───
            col1, col2 = st.columns(2)

            with col1:
                # Summary
                st.markdown("### 📋 Meeting Summary")
                st.info(results["summary"])

                # Key Points
                st.markdown("### 🔑 Key Points")
                st.success(results["key_points"])

            with col2:
                # Action Items
                st.markdown("### ✅ Action Items")
                st.warning(results["action_items"])

                # Decisions
                st.markdown("### 🎯 Decisions Made")
                st.error(results["decisions"])

            st.divider()

            # ─── DOWNLOAD REPORT ───
            st.subheader("📥 Download Report")

            report = f"""
AI MEETING ANALYSIS REPORT
Generated by AI Meeting Summariser
{'='*50}

FILE: {uploaded_file.name}

{'='*50}
MEETING SUMMARY
{'='*50}
{results['summary']}

{'='*50}
KEY POINTS DISCUSSED
{'='*50}
{results['key_points']}

{'='*50}
ACTION ITEMS
{'='*50}
{results['action_items']}

{'='*50}
DECISIONS MADE
{'='*50}
{results['decisions']}

{'='*50}
TRANSCRIPT
{'='*50}
{transcript}
"""

            st.download_button(
                label="📥 Download Full Report (.txt)",
                data=report,
                file_name=f"meeting_analysis_{uploaded_file.name}.txt",
                mime="text/plain",
                use_container_width=True
            )

            st.success("✅ Analysis complete!")

        except Exception as e:
            st.error(f"Error processing file: {str(e)}")

        finally:
            # Clean up temp file
            os.unlink(tmp_path)

else:
    # ─── INSTRUCTIONS ───
    st.info("👆 Upload a meeting transcript (.txt) or audio file (.mp3, .wav, .m4a) to get started!")

    st.divider()
    st.subheader("✨ What this app does:")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.markdown("#### 📝 Transcribes")
        st.markdown("Converts audio to text using Whisper AI")

    with col2:
        st.markdown("#### 📋 Summarises")
        st.markdown("Generates concise meeting summary")

    with col3:
        st.markdown("#### ✅ Action Items")
        st.markdown("Extracts tasks with owners and deadlines")

    with col4:
        st.markdown("#### 🎯 Decisions")
        st.markdown("Identifies all decisions made")